/**
 * ChatStore — JSONL-per-session persistence for chat history.
 *
 * Each line is one persisted turn. The shape grew with the agentic loop:
 *
 *   v1 (legacy text-only):
 *     { ts, role: 'user'|'assistant', content: string }
 *
 *   v2 (current — also supports tool blocks):
 *     { ts, role, content: string | ContentBlock[] }
 *
 * load() handles both transparently — older sessions keep replaying as
 * plain text turns.
 *
 * Layout (0.4.66 — project-scoped):
 *   <dataRoot>/chat-sessions/
 *     _orphan/                              ← chats with no project
 *       2026-06-11_<uuid>.jsonl
 *     <project name>/                       ← per-project folder (sanitized name)
 *       2026-06-11_<uuid>.jsonl
 *
 * Older builds wrote every file flat into chat-sessions/. ChatPanelV2
 * runs a one-shot migration on boot to move existing files into the
 * right subfolder based on ProjectStore.sessions.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { ContentBlock, UsageDelta } from './ChatStreamer';

/** Subfolder used for chats with no project. */
export const ORPHAN_FOLDER = '_orphan';

/** Turn a project name into a filesystem-safe folder name. Empty / falsy
 *  inputs map to ORPHAN_FOLDER so we always end up with a real directory. */
export function sanitizeProjectFolder(name: string | undefined | null): string {
  const raw = (name ?? '').trim();
  if (!raw) return ORPHAN_FOLDER;
  const cleaned = raw
    .replace(/[\\/:*?"<>|\x00-\x1f]/g, '-')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^\.+$/, '_')
    .slice(0, 120);
  return cleaned || ORPHAN_FOLDER;
}

export interface AgentThreadMeta {
  schema: 1;
  rootChatId: string;
  agentId: string;
  parentAgentId?: string;
  ownerAgentId?: string;
  runId?: string;
  depth: number;
  task: string;
  model: string;
  effort: string;
  createdAt: number;
  finishedAt?: number;
  status: string;
  submitted?: boolean;
  /** True when the backend auto-transferred this agent (model skipped
   *  agent_transfer). Persisted so the dock indicator survives reload. */
  autoTransferred?: boolean;
  /** True when the backend context guard fired (runtime crossed ~85% of the
   *  window → auto-interrupt + synthesize/transfer injection). Persisted so the
   *  dock badge survives reload. */
  contextGuarded?: boolean;
  maxTurns?: number;
  usage?: UsageDelta;
  costUsd?: number;
  contextMax?: number;
  result?: string;
  error?: string;
  resultInjected?: boolean;
  returnBudgetTokens?: number;
  returnState?: 'pending' | 'summarizing' | 'ready' | 'delivered' | 'failed';
  handoffResult?: string;
  handoffTokens?: number;
  handoffBudgetTokens?: number;
  deliveredAt?: number;
  artifacts?: Array<{
    id: string;
    name: string;
    mediaType: string;
    size: number;
    sourceAgentId: string;
    savedAt: number;
  }>;
  /** Artifact ids already handed to the parent via agent_transfer. */
  transferredArtifactIds?: string[];
}

export interface PersistedMessage {
  ts:      number;
  role:    'user' | 'assistant';
  content: string | ContentBlock[];
  /** 0.4.163 — set on user turns generated by AURA internally (continuation
   *  hints, dev-mode outer-loop "(continue)"). Model still sees these in
   *  history so it can react, but the webview skips rendering them as a
   *  standalone user bubble and shows a compact hint card instead. */
  synthetic?: boolean;
  /** 0.4.229 — semantic role of a synthetic turn. Only 'compact' today:
   *  a compact-summary marker written into full history so reload can
   *  reconstruct both the FE card and the runtime payload without a
   *  separate .compact.md file. */
  kind?: 'compact' | 'agent-handoff';
  /** Source revisions embedded in a pending manual agent handoff turn. */
  agentHandoffs?: Array<{
    sourceAgentId: string;
    sourceTask: string;
    revision: string;
    text: string;
  }>;
  /** 0.4.189 — structured metadata for files the user attached to this
   *  turn. When present, the webview renders a chip row above the text on
   *  both send and reload; without it we'd only have the augmented text
   *  the model saw (`### Attached: ...`) which isn't chip-shaped. */
  attachments?: PersistedAttachment[];
}

export interface PersistedAttachment {
  filename:   string;
  hash:       string;
  mimeType?:  string;
  sizeBytes?: number;
  notes?:     string;
  /** Absolute path to the .md MinerU produced (see AttachmentParser). */
  resultPath?: string;
  /** Absolute path to the copied original (kept so the user can re-download). */
  origPath?:  string;
}

export class ChatStore {
  private file?: string;
  private runtimeFile?: string;

  /**
   * @param sessionsRoot  <dataRoot>/chat-sessions (the parent of all project folders)
   * @param sessionId     chat id
   * @param projectFolder sanitized project folder name; defaults to _orphan
   */
  constructor(
    private readonly sessionsRoot:   string,
    private readonly sessionId:      string,
    private readonly projectFolder:  string = ORPHAN_FOLDER,
    private readonly agentId?:       string,
  ) {
    if (agentId && !ChatStore.isValidAgentId(agentId)) {
      throw new Error(`invalid agent id: ${agentId}`);
    }
  }

  static isValidAgentId(agentId: string): boolean {
    return /^agt_[0-9a-f]{12}$/i.test(agentId);
  }

  static agentSuffix(agentId: string): string {
    if (!ChatStore.isValidAgentId(agentId)) throw new Error(`invalid agent id: ${agentId}`);
    return `.agent-${agentId}`;
  }

  private get dir(): string {
    return path.join(this.sessionsRoot, this.projectFolder);
  }

  /** Create the file lazily so empty sessions don't litter the directory.
   *  If a previous-day file for this sessionId already exists anywhere
   *  in this project's folder, reuse it so a chat that spanned midnight
   *  keeps appending to the same JSONL. */
  private async ensureFile() {
    if (this.file) return this.file;
    await fs.mkdir(this.dir, { recursive: true });
    let existing: string | null = null;
    let existingMtime = 0;
    try {
      const entries = await fs.readdir(this.dir);
      for (const n of entries) {
        const suffix = `_${this.sessionId}${this.agentId ? ChatStore.agentSuffix(this.agentId) : ''}.jsonl`;
        if (!n.endsWith(suffix)) continue;
        const p = path.join(this.dir, n);
        try {
          const st = await fs.stat(p);
          if (st.mtimeMs > existingMtime) {
            existingMtime = st.mtimeMs;
            existing = p;
          }
        } catch { /* ignore */ }
      }
    } catch { /* fresh dir */ }
    if (existing) {
      this.file = existing;
      return existing;
    }
    const day = new Date().toISOString().slice(0, 10);
    const agentSuffix = this.agentId ? ChatStore.agentSuffix(this.agentId) : '';
    this.file = path.join(this.dir, `${day}_${this.sessionId}${agentSuffix}.jsonl`);
    return this.file;
  }

  async append(msg: PersistedMessage) {
    const f = await this.ensureFile();
    await fs.appendFile(f, JSON.stringify(msg) + '\n', 'utf8');
  }

  async writeAgentMeta(meta: AgentThreadMeta): Promise<void> {
    if (!this.agentId || meta.agentId !== this.agentId || meta.rootChatId !== this.sessionId) {
      throw new Error('agent metadata does not match store scope');
    }
    const f = await this.ensureFile();
    let exists = false;
    try { exists = (await fs.stat(f)).size > 0; } catch { /* new file */ }
    if (!exists) {
      await fs.appendFile(f, JSON.stringify({ type: 'agent_meta', ...meta }) + '\n', 'utf8');
    }
  }

  async updateAgentMeta(patch: Partial<AgentThreadMeta>): Promise<void> {
    if (!this.agentId) return;
    const f = await this.ensureFile();
    let raw = '';
    try { raw = await fs.readFile(f, 'utf8'); } catch { return; }
    const lines = raw.split('\n');
    if (!lines[0]?.trim()) return;
    try {
      const obj = JSON.parse(lines[0]);
      if (obj?.type !== 'agent_meta' || obj.agentId !== this.agentId) return;
      lines[0] = JSON.stringify({ ...obj, ...patch, type: 'agent_meta' });
      await fs.writeFile(f, lines.join('\n'), 'utf8');
    } catch { /* leave transcript intact */ }
  }

  static async agentMeta(file: string): Promise<AgentThreadMeta | null> {
    let raw = '';
    try { raw = await fs.readFile(file, 'utf8'); } catch { return null; }
    for (const line of raw.split('\n')) {
      if (!line.trim()) continue;
      try {
        const obj = JSON.parse(line);
        if (obj?.type === 'agent_meta' && ChatStore.isValidAgentId(String(obj.agentId || ''))) {
          const { type: _type, ...meta } = obj;
          return meta as AgentThreadMeta;
        }
      } catch { return null; }
      break;
    }
    return null;
  }

  static async agentFilesForChatId(sessionsRoot: string, chatId: string): Promise<string[]> {
    const all = await ChatStore.walkJsonl(sessionsRoot);
    return all.filter(p => {
      const n = path.basename(p);
      return n.includes(`_${chatId}.agent-`) && n.endsWith('.jsonl');
    }).sort();
  }

  static async loadAgent(sessionsRoot: string, chatId: string, agentId: string): Promise<PersistedMessage[]> {
    if (!ChatStore.isValidAgentId(agentId)) return [];
    const suffix = `_${chatId}${ChatStore.agentSuffix(agentId)}.jsonl`;
    const files = (await ChatStore.walkJsonl(sessionsRoot)).filter(p => path.basename(p).endsWith(suffix)).sort();
    const out: PersistedMessage[] = [];
    for (const f of files) out.push(...await ChatStore.load(f));
    return out;
  }

  static async deleteAgent(sessionsRoot: string, chatId: string, agentId: string): Promise<void> {
    if (!ChatStore.isValidAgentId(agentId)) throw new Error(`invalid agent id: ${agentId}`);
    const suffix = `_${chatId}${ChatStore.agentSuffix(agentId)}.jsonl`;
    const files = (await ChatStore.walkJsonl(sessionsRoot))
      .filter(p => path.basename(p).endsWith(suffix));
    for (const file of files) {
      await fs.unlink(file).catch(() => {});
      await fs.unlink(file.replace(/\.jsonl$/, '.runtime.jsonl')).catch(() => {});
    }
  }

  /** Replace the entire backing file with the given messages. Used by the
   *  per-turn delete button so the JSONL stays in sync with in-memory
   *  history after the user excises a turn pair. */
  async rewrite(msgs: PersistedMessage[]): Promise<void> {
    const f = await this.ensureFile();
    const lines = msgs.map(m => JSON.stringify(m)).join('\n');
    await fs.writeFile(f, lines ? lines + '\n' : '', 'utf8');
  }

  /** Rewrite an agent transcript while preserving its mandatory metadata line. */
  async rewriteAgent(msgs: PersistedMessage[]): Promise<void> {
    if (!this.agentId) return this.rewrite(msgs);
    const f = await this.ensureFile();
    let metaLine = '';
    try {
      const first = (await fs.readFile(f, 'utf8')).split('\n')[0];
      const parsed = JSON.parse(first);
      if (parsed?.type === 'agent_meta' && parsed.agentId === this.agentId) metaLine = first;
    } catch { /* malformed/missing meta remains absent */ }
    const body = msgs.map(m => JSON.stringify(m));
    const lines = metaLine ? [metaLine, ...body] : body;
    await fs.writeFile(f, lines.length ? lines.join('\n') + '\n' : '', 'utf8');
  }

  /** 0.4.217 — runtime file lives beside the full JSONL as
   *  `<date>_<chatId>.runtime.jsonl`. Same schema. It is the payload that
   *  actually rides to the API. Compact rewrites this file to a single
   *  compact-summary turn; the full JSONL is never touched by compact. */
  private async ensureRuntimeFile(): Promise<string> {
    if (this.runtimeFile) return this.runtimeFile;
    const full = await this.ensureFile();
    this.runtimeFile = full.replace(/\.jsonl$/, '.runtime.jsonl');
    return this.runtimeFile;
  }

  async appendRuntime(msg: PersistedMessage): Promise<void> {
    const f = await this.ensureRuntimeFile();
    await fs.appendFile(f, JSON.stringify(msg) + '\n', 'utf8');
  }

  async overwriteRuntime(msgs: PersistedMessage[]): Promise<void> {
    const f = await this.ensureRuntimeFile();
    const lines = msgs.map(m => JSON.stringify(m)).join('\n');
    await fs.writeFile(f, lines ? lines + '\n' : '', 'utf8');
  }

  /** Return absolute path to the runtime file (creating the directory if
   *  needed but not the file). Used by external callers that read the
   *  runtime to build API payloads. */
  async runtimeFilePath(): Promise<string> {
    return this.ensureRuntimeFile();
  }

  /** Load runtime file, or an empty list if it doesn't exist yet. Same
   *  parser as full history. */
  static async loadRuntime(runtimeFile: string): Promise<PersistedMessage[]> {
    return ChatStore.load(runtimeFile);
  }

  /** Locate the runtime file for a chatId across project folders, or null
   *  if it doesn't exist. Runtime files share the date/id prefix with
   *  their full JSONL sibling. */
  static async runtimeFileForChatId(sessionsRoot: string, chatId: string): Promise<string | null> {
    const files = await ChatStore.walkJsonl(sessionsRoot);
    const candidates = files
      .filter(p => path.basename(p).endsWith(`_${chatId}.runtime.jsonl`))
      .sort();
    return candidates.length ? candidates[candidates.length - 1] : null;
  }

  /** Walk every .jsonl (excluding .runtime.jsonl — that's a shadow file
   *  managed separately) under sessionsRoot — first-level project folders
   *  AND any file still at the flat root from before 0.4.66. */
  private static async walkJsonl(sessionsRoot: string): Promise<string[]> {
    const out: string[] = [];
    let entries: import('fs').Dirent[] = [];
    try {
      entries = await fs.readdir(sessionsRoot, { withFileTypes: true });
    } catch {
      return out;
    }
    for (const ent of entries) {
      const full = path.join(sessionsRoot, ent.name);
      if (ent.isDirectory()) {
        let sub: string[] = [];
        try { sub = await fs.readdir(full); } catch { continue; }
        for (const n of sub) {
          if (!n.endsWith('.jsonl')) continue;
          if (n.endsWith('.runtime.jsonl')) continue;
          out.push(path.join(full, n));
        }
      } else if (ent.isFile() && ent.name.endsWith('.jsonl') && !ent.name.endsWith('.runtime.jsonl')) {
        out.push(full);
      }
    }
    return out;
  }

  /** Find the most-recently-modified .jsonl anywhere under sessionsRoot. */
  static async findLatest(sessionsRoot: string): Promise<string | null> {
    const files = await ChatStore.walkJsonl(sessionsRoot);
    if (!files.length) return null;
    const stats = await Promise.all(files.map(async p => {
      try { return { p, mtime: (await fs.stat(p)).mtimeMs }; }
      catch { return { p, mtime: 0 }; }
    }));
    stats.sort((a, b) => b.mtime - a.mtime);
    return stats[0].mtime ? stats[0].p : null;
  }

  /** Summary used by the history dropdown — title is the first user line,
   *  trimmed to 60 chars. Walks every project folder. */
  static async listSessions(sessionsRoot: string): Promise<Array<{
    file: string; id: string; title: string; mtime: number; messageCount: number;
  }>> {
    const files = (await ChatStore.walkJsonl(sessionsRoot))
      .filter(p => !path.basename(p).includes('.agent-'));
    if (!files.length) return [];

    const byId = new Map<string, { files: string[]; mtime: number }>();
    for (const file of files) {
      let mtime = 0;
      try { mtime = (await fs.stat(file)).mtimeMs; } catch { continue; }
      const base = path.basename(file);
      const id   = base.replace(/\.jsonl$/, '').split('_').pop() || base;
      const cur = byId.get(id);
      if (cur) {
        cur.files.push(file);
        if (mtime > cur.mtime) cur.mtime = mtime;
      } else {
        byId.set(id, { files: [file], mtime });
      }
    }

    const out: Array<{ file: string; id: string; title: string; mtime: number; messageCount: number }> = [];
    for (const [id, grp] of byId.entries()) {
      grp.files.sort();
      const msgs: PersistedMessage[] = [];
      for (const f of grp.files) msgs.push(...(await ChatStore.load(f)));
      if (!msgs.length) continue;
      const firstUser = msgs.find(m => m.role === 'user');
      const title = textOf(firstUser?.content ?? msgs[0].content)
        .replace(/\s+/g, ' ').trim().slice(0, 60) || '(empty)';
      out.push({
        file: grp.files[grp.files.length - 1],
        id,
        title,
        mtime: grp.mtime,
        messageCount: msgs.length,
      });
    }
    out.sort((a, b) => b.mtime - a.mtime);
    return out;
  }

  /** Load every JSONL file for a chatId in chronological order and
   *  return the merged message list. Walks every project folder. */
  static async loadByChatId(sessionsRoot: string, chatId: string): Promise<PersistedMessage[]> {
    const all = await ChatStore.walkJsonl(sessionsRoot);
    const files = all
      .filter(p => path.basename(p).endsWith(`_${chatId}.jsonl`))
      .sort((a, b) => path.basename(a).localeCompare(path.basename(b)));
    const out: PersistedMessage[] = [];
    for (const f of files) {
      out.push(...(await ChatStore.load(f)));
    }
    return out;
  }

  /** Locate JSONL files for a chatId across all project folders.
   *  Used by callers that need to move/delete a chat's persisted state. */
  static async filesForChatId(sessionsRoot: string, chatId: string): Promise<string[]> {
    const all = await ChatStore.walkJsonl(sessionsRoot);
    return all.filter(p => path.basename(p).endsWith(`_${chatId}.jsonl`)).sort();
  }

  /** Read every line of a session file, skipping malformed ones. */
  static async load(file: string): Promise<PersistedMessage[]> {
    let raw = '';
    try { raw = await fs.readFile(file, 'utf8'); } catch { return []; }
    const out: PersistedMessage[] = [];
    for (const ln of raw.split('\n')) {
      if (!ln.trim()) continue;
      try {
        const obj = JSON.parse(ln);
        if (obj && (obj.role === 'user' || obj.role === 'assistant')
            && (typeof obj.content === 'string' || Array.isArray(obj.content))) {
          const rec: PersistedMessage = { ts: obj.ts ?? 0, role: obj.role, content: obj.content };
          if (obj.synthetic === true) rec.synthetic = true;
          if (obj.kind === 'compact' || obj.kind === 'agent-handoff') rec.kind = obj.kind;
          if (Array.isArray(obj.agentHandoffs)) rec.agentHandoffs = obj.agentHandoffs;
          if (Array.isArray(obj.attachments)) rec.attachments = obj.attachments;
          out.push(rec);
        }
      } catch { /* skip malformed line */ }
    }
    return out;
  }
}

/** Best-effort text extraction for UI labels. */
export function textOf(content: string | ContentBlock[]): string {
  if (typeof content === 'string') return content;
  return content
    .map(b => {
      if (b.type === 'text') return b.text;
      if (b.type === 'tool_use') return `[tool ${b.name}]`;
      if (b.type === 'tool_result') return typeof b.content === 'string' ? b.content : '[tool_result]';
      if (b.type === 'image') return '[image]';
      return '';
    })
    .filter(Boolean)
    .join(' ');
}
